### PR TITLE
Timberwolff added features

### PR DESCRIPTION
**Pull request by Timberwolff**
I added several features to your master code, because I want more control over the unit. 
The checksum verification did not work for me, that is why I commented it out.
This code is working fine for me and I tested it using my Kunkin KP184.

### CODE REVIEW

**Comment by Timberwolff** [comment]
This is my first contribution on GitHub. I hope I did it right :-)

**Comment by cskilbeck** [comment]
Thanks so much for this contribution, I love it. I'm a bit concerned about the checksum thing though - it works for me and I'm not sure I want to just remove it altogether. Perhaps an option to disable it in the command line would be better?

**Comment by cskilbeck** [comment]
Also, what didn't work about the ramp function?

**Comment by Timberwolff** [comment]
I created a video to show the difference of the two ramp functions:
[Youtube Video](https://youtu.be/KHYFhrHOrZ4)
Your implementation is not working for me. Or at least my system is too fast (i7-8700K)?

**Comment by cskilbeck** [comment]
Ah! Thank you so much for making this video, I think I see the problem, a silly bug in my code - I used the wrong value in this line:

** var step_time = TimeSpan.FromMilliseconds(step);
**
it should be

** var step_time = TimeSpan.FromMilliseconds(interval_ms);****
**

I think I didn't notice because I was using values for `step` which happened to be similar to `interval_ms`

Would you mind trying it with this change? My setup is all packed away now.

If this is a fix then I think we should stick with the original ramp function as it compensates for the serial communication time which should make the step time as accurate as possible.

**Comment by Timberwolff** [comment]
I changed the code. It is a little bit better now, but still not accurate.
I did a quick comparison using %TIME% in a batch file:

E:\Modbus\modbus-master\bin\Debug>test
"ramp version 1"
 0:14:32,24
ramp                :Ramp: from 100 to 1000 in steps of 100 at intervals of 2000
 0:14:42,40
"ramp version 2"
 0:14:42,40
ramp2               :Ramp2: from 100 to 1000 in steps of 100 at intervals of 2000
 0:15:02,62

This is how my test. bat looks like:
`@echo` off
echo "ramp version 1"
echo %TIME%
KP184.exe port com11; address 1; ramp 100 1000 100 2000
echo %TIME%
echo "ramp version 2"
echo %TIME%
KP184.exe port com11; address 1; ramp2 100 1000 100 2000
echo %TIME%

There is maybe another bug in your code?

**Comment by cskilbeck** [comment]
Tell you what, I'll fix it today and check in, then we can merge in the rest of your changes, which look awesome. I do want to keep the checksum on by default, though, so I'll add a switch to disable it.

**Comment by cskilbeck** [comment]
I checked in some changes, the ramp function seems to work well for me now, see log below. I also added `checksum [true|false]` to enable or disable checksum checking, defaults to true. Also added timestamps to log messages.

```
Debug    16:01:54.802 level               :Setting log level to Debug
Verbose  16:01:54.818 port                :COM Port: com5
Info     16:01:54.818 checksum            :Checksum checking: False
Verbose  16:01:54.819 baud                :BAUD rate: 57600
Verbose  16:01:54.819 address             :Device address: 1
Verbose  16:01:54.819 switch              :Turning load switch on
Verbose  16:01:54.820 set_load_switch     :Set switch on
Verbose  16:01:54.821 open                :Opening serial port 'com5' at 57600 baud
Info     16:01:54.833 ramp                :Ramp: from 0 to 500 in steps of 100 at intervals of 1000
Verbose  16:01:54.833 set_current         :Set current to 0mA
Verbose  16:01:55.833 set_current         :Set current to 100mA
Verbose  16:01:56.834 set_current         :Set current to 200mA
Verbose  16:01:57.834 set_current         :Set current to 300mA
Verbose  16:01:58.833 set_current         :Set current to 400mA
Verbose  16:01:59.834 set_current         :Set current to 500mA
Verbose  16:02:00.834 switch              :Turning load switch off
Verbose  16:02:00.834 set_load_switch     :Set switch off
```

**Comment by cskilbeck** [comment]
ah, my apologies, I found the actual bug in the ramp() function, have checked in a fix, also added a delay command line option which I found useful

**Comment by cskilbeck** [comment]
I merged your pull request, I've left your ramp2 function in place, although the original has more accurate timing, especially with slow baud rates. Thanks so much for your changes, very useful!

**Pull request merged**
